[package]
name = "cache"
version = "0.3.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2024"
publish = false

[dependencies]
async-cell-lock = { git = "https://github.com/danylaporte/async-cell-lock.git" }
